apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: elf-clusterclass
spec:
  controlPlane:
    machineInfrastructure:
      ref:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: ElfMachineTemplate
        name: elf-clusterclass-controlplane-machine-template
        namespace: default
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: KubeadmControlPlaneTemplate
      name: elf-clusterclass-controlplane
      namespace: default
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: ElfClusterTemplate
      name: elf-clusterclass
      namespace: default
  patches:
  - definitions:
    - jsonPatches:
      - op: add
        path: /spec/template/spec/controlPlaneEndpoint
        valueFrom:
          template: |
            host: '{{ .controlPlaneIpAddr }}'
            port: 6443
      - op: add
        path: /spec/template/spec/cluster
        valueFrom:
          variable: elfCluster
      - op: add
        path: /spec/template/spec/tower/server
        valueFrom:
          variable: infraServer.server
      - op: add
        path: /spec/template/spec/tower/username
        valueFrom:
          variable: infraServer.username
      - op: add
        path: /spec/template/spec/tower/password
        valueFrom:
          variable: infraServer.password
      selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: ElfClusterTemplate
        matchResources:
          infrastructureCluster: true
    name: infraClusterSubstitutions
  - definitions:
    - jsonPatches:
      - op: add
        path: /spec/template/spec/kubeadmConfigSpec/files/0/content
        valueFrom:
          variable: kubeVipPodManifest
      selector:
        apiVersion: controlplane.cluster.x-k8s.io/v1beta1
        kind: KubeadmControlPlaneTemplate
        matchResources:
          controlPlane: true
    name: kubeVipEnabled
  - definitions:
    - jsonPatches:
      - op: add
        path: /spec/template/spec/kubeadmConfigSpec/clusterConfiguration/imageRepository
        valueFrom:
          variable: imageRepository
      selector:
        apiVersion: controlplane.cluster.x-k8s.io/v1beta1
        kind: KubeadmControlPlaneTemplate
        matchResources:
          controlPlane: true
    name: imageRepository
  variables:
  - name: elfCluster
    required: true
    schema:
      openAPIV3Schema:
        description: ElfCluster is a unique identifier for a ELF cluster.
        type: string
  - name: infraServer
    required: true
    schema:
      openAPIV3Schema:
        properties:
          password:
            type: string
          server:
            type: string
          username:
            type: string
        type: object
  - name: controlPlaneIpAddr
    required: true
    schema:
      openAPIV3Schema:
        description: Floating VIP for the control plane.
        type: string
  - name: kubeVipPodManifest
    required: true
    schema:
      openAPIV3Schema:
        description: kube-vip manifest for the control plane.
        type: string
  - name: imageRepository
    required: true
    schema:
      openAPIV3Schema:
        default: k8s.gcr.io
        description: ImageRepository is the container registry to pull images from.
        example: k8s.gcr.io
        type: string
  workers:
    machineDeployments:
    - class: elf-clusterclass-worker
      template:
        bootstrap:
          ref:
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
            kind: KubeadmConfigTemplate
            name: elf-clusterclass-worker-bootstrap-template
            namespace: default
        infrastructure:
          ref:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: ElfMachineTemplate
            name: elf-clusterclass-worker-machine-template
            namespace: default
        metadata: {}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ElfClusterTemplate
metadata:
  name: elf-clusterclass
  namespace: default
spec:
  template:
    spec:
      controlPlaneEndpoint:
        host: 127.0.0.1
        port: 6443
      tower: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlaneTemplate
metadata:
  name: elf-clusterclass-controlplane
  namespace: default
spec:
  template:
    spec:
      kubeadmConfigSpec:
        clusterConfiguration:
          apiServer:
            extraArgs: null
          controllerManager:
            extraArgs: null
        files:
        - owner: root:root
          path: /etc/kubernetes/manifests/kube-vip.yaml
        initConfiguration:
          nodeRegistration:
            kubeletExtraArgs: null
            name: '{{ ds.meta_data.hostname }}'
        joinConfiguration:
          nodeRegistration:
            kubeletExtraArgs: null
            name: '{{ ds.meta_data.hostname }}'
        preKubeadmCommands:
        - hostname "{{ ds.meta_data.hostname }}"
        - echo "::1         ipv6-localhost ipv6-loopback" >/etc/hosts
        - echo "127.0.0.1   localhost" >>/etc/hosts
        - echo "127.0.0.1   {{ ds.meta_data.hostname }}" >>/etc/hosts
        - echo "{{ ds.meta_data.hostname }}" >/etc/hostname
        useExperimentalRetryJoin: true
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ElfMachineTemplate
metadata:
  name: elf-clusterclass-controlplane-machine-template
  namespace: default
spec:
  template:
    spec:
      autoSchedule: true
      ha: true
      network:
        devices:
        - networkIndex: 0
          networkType: ipv4_dhcp
        vlan: 576ad467-d09e-4235-9dec-b615814ddc7e_c8a1e42d-e0f3-4d50-a190-53209a98f157
      template: 336820d7-5ba5-4707-9d0c-8f3e583b950f
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ElfMachineTemplate
metadata:
  name: elf-clusterclass-worker-machine-template
  namespace: default
spec:
  template:
    spec:
      autoSchedule: true
      ha: true
      network:
        devices:
        - networkIndex: 0
          networkType: ipv4_dhcp
        vlan: 576ad467-d09e-4235-9dec-b615814ddc7e_c8a1e42d-e0f3-4d50-a190-53209a98f157
      template: 336820d7-5ba5-4707-9d0c-8f3e583b950f
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: elf-clusterclass-worker-bootstrap-template
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs: null
          name: '{{ ds.meta_data.hostname }}'
      preKubeadmCommands:
      - hostname "{{ ds.meta_data.hostname }}"
      - echo "::1         ipv6-localhost ipv6-loopback" >/etc/hosts
      - echo "127.0.0.1   localhost" >>/etc/hosts
      - echo "127.0.0.1   {{ ds.meta_data.hostname }}" >>/etc/hosts
      - echo "{{ ds.meta_data.hostname }}" >/etc/hostname
