apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: elfk8s
  name: elfk8s
  namespace: default
spec:
  topology:
    class: elf-clusterclass
    controlPlane:
      replicas: 1
    variables:
    - name: elfCluster
      value: 576ad467-d09e-4235-9dec-b615814ddc7e
    - name: infraServer
      value:
        password: K5yt3hcjtUE4Teqe
        server: cape.dev-cloudtower.smartx.com
        username: system-service
    - name: kubeVipPodManifest
      value: |
        apiVersion: v1
        kind: Pod
        metadata:
          creationTimestamp: null
          name: kube-vip
          namespace: kube-system
        spec:
          containers:
          - args:
            - start
            env:
            - name: vip_arp
              value: "true"
            - name: vip_leaderelection
              value: "true"
            - name: vip_interface
              value: "eth0"
            - name: address
              value: 192.168.30.158
            - name: vip_leaseduration
              value: "15"
            - name: vip_renewdeadline
              value: "10"
            - name: vip_retryperiod
              value: "2"
            image: ghcr.io/kube-vip/kube-vip:v0.3.5
            imagePullPolicy: IfNotPresent
            name: kube-vip
            resources: {}
            securityContext:
              capabilities:
                add:
                - NET_ADMIN
                - SYS_TIME
            volumeMounts:
            - mountPath: /etc/kubernetes/admin.conf
              name: kubeconfig
          hostNetwork: true
          volumes:
          - hostPath:
              path: /etc/kubernetes/admin.conf
              type: FileOrCreate
            name: kubeconfig
        status: {}
    - name: controlPlaneIpAddr
      value: 192.168.30.158
    - name: imageRepository
      value: registry.cn-hangzhou.aliyuncs.com/google_containers
    version: v1.20.6
    workers:
      machineDeployments:
      - class: elf-clusterclass-worker
        metadata: {}
        name: md-0
        replicas: 1
