---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: '${CLUSTER_NAME}'
  name: '${CLUSTER_NAME}'
  namespace: '${NAMESPACE}'
spec:
  topology:
    class: '${CLUSTER_CLASS_NAME}'
    controlPlane:
      replicas: ${CONTROL_PLANE_MACHINE_COUNT}
    variables:
    - name: elfCluster
      value: '${ELF_CLUSTER}'
    - name: infraServer
      value:
        server: '${TOWER_SERVER}'
        username: '${TOWER_USERNAME}'
        password: '${TOWER_PASSWORD}'
        authMode: ${TOWER_AUTH_MODE:=LOCAL}
        skipTLSVerify: ${TOWER_SKIP_TLS_VERIFY:=false}
    - name: kubeVipPodManifest
      value: |
        apiVersion: v1
        kind: Pod
        metadata:
          creationTimestamp: null
          name: kube-vip
          namespace: kube-system
        spec:
          containers:
          - args:
            - manager
            env:
            - name: cp_enable
              value: "true"
            - name: vip_interface
              value: ${VIP_NETWORK_INTERFACE:="ens4"}
            - name: address
              value: ${CONTROL_PLANE_ENDPOINT_IP}
            - name: port
              value: "6443"
            - name: vip_arp
              value: "true"
            - name: vip_leaderelection
              value: "true"
            - name: vip_leaseduration
              value: "15"
            - name: vip_renewdeadline
              value: "10"
            - name: vip_retryperiod
              value: "2"
            image: ${IMAGE_REPOSITORY:=registry.cn-hangzhou.aliyuncs.com/google_containers}/kube-vip/kube-vip:v0.5.7
            imagePullPolicy: IfNotPresent
            name: kube-vip
            resources: {}
            securityContext:
              capabilities:
                add:
                - NET_ADMIN
                - NET_RAW
            volumeMounts:
            - mountPath: /etc/kubernetes/admin.conf
              name: kubeconfig
          hostAliases:
          - hostnames:
            - kubernetes
            ip: 127.0.0.1
          hostNetwork: true
          volumes:
          - hostPath:
              path: /etc/kubernetes/admin.conf
              type: FileOrCreate
            name: kubeconfig
        status: {}
    - name: controlPlaneIpAddr
      value: ${CONTROL_PLANE_ENDPOINT_IP}
    - name: imageRepository
      value: ${IMAGE_REPOSITORY:=registry.cn-hangzhou.aliyuncs.com/google_containers}
    - name: vmTemplate
      value: ${VM_TEMPLATE}
    version: '${KUBERNETES_VERSION}'
    workers:
      machineDeployments:
      - class: ${CLUSTER_CLASS_NAME}-worker
        metadata: {}
        name: md-0
        replicas: ${WORKER_MACHINE_COUNT}
